// zzaria/client/src/app/components/footer/footer.component.ts
import { Component, Input } from "@angular/core";
import { footerLinks } from "./footer-links";

@Component({
    selector: "app-footer",
    templateUrl: "./footer.component.html",
    styleUrls: ["./footer.component.scss"],
})
export class FooterComponent {
    @Input()
    public color: "bg" | "bg-alt";

    public links = footerLinks;

    constructor() {}
}

<footer [class]="color">
    <h4>© 2020 TTS. All rights reserved.</h4>

    <section class="icons">
        <a *ngFor="let link of links" [href]="link.url" mat-button>
            <img [src]="link.svgPath">
        </a>
    </section>

    <h4>Made with 💖 by TTS Mods.</h4>
</footer>

// src/ui/Footer/Footer.tsx
import { Button } from "@material-ui/core";
import React from "react";
import { footerLinks } from "./FooterLinks";

interface FooterProps {
    color: 'bg' | 'bg-alt';
}

export const Footer: React.FC<FooterProps> = ({ color }) => (
    <div className="footer-ui-component">
        <footer className={color}>
            <h4>© 2020 TTS. All rights reserved.</h4>

            <section className="icons">
                {footerLinks.map((l) => (
                    <Button href={l.url}>
                        <img src={l.svgPath} />
                    </Button>
                ))}
            </section>

            <h4>Made with 💖 by TTS Mods.</h4>
        </footer>
    </div>
)
